export interface ChecklistItem {
  id: number;
  text: string;
  depth: number;
  checked: boolean;
}

export interface ChecklistGroup {
  title: string;
  emoji: string;
  items: ChecklistItem[];
}

let cid = 1001;
const nid = () => cid++;

const item = (text: string, checked: boolean, depth: number = 0): ChecklistItem => ({
  id: nid(), text, depth, checked,
});

const G = (title: string, emoji: string, items: ChecklistItem[]): ChecklistGroup => ({ title, emoji, items });

const groups: ChecklistGroup[] = [
  G('Databases', '1️⃣', [
    item('Relational Databases', true),
    item('B+ Tree Indexing', true),
    item('Understand node structure (internal vs leaf nodes)', true, 1),
    item('Understand branching factor', true, 1),
    item('Understand disk I/O reduction logic', true, 1),
    item('Clustered vs Non-Clustered Index', true),
    item('Storage layout difference', true, 1),
    item('Performance implications', true, 1),
    item('Covering Index', true),
    item('Understand index-only scan', true, 1),
    item('When it avoids table lookup', true, 1),
    item('Query Execution Plan', true),
    item('Read EXPLAIN output', true, 1),
    item('Identify full table scan', true, 1),
    item('Identify index scan', true, 1),
    item('Write-Ahead Logging (WAL)', true),
    item('Understand log-first write principle', true, 1),
    item('Crash recovery flow', true, 1),
    item('Checkpointing', true),
    item('Why checkpoints exist', true, 1),
    item('Trade-off between frequency & performance', true, 1),
    item('ACID (Implementation Level)', true),
    item('Atomicity via WAL', true, 1),
    item('Consistency via constraints', true, 1),
    item('Isolation via locking/MVCC', true, 1),
    item('Durability via fsync', true, 1),
    item('Locking vs MVCC', true),
    item('Read/write blocking behavior', true, 1),
    item('Snapshot visibility', true, 1),
    item('Isolation Levels', true),
    item('Dirty Read', true, 1),
    item('Non-Repeatable Read', true, 1),
    item('Phantom Read', true, 1),
    item('MVCC Mechanics', true),
    item('Version chains', true, 1),
    item('Snapshot creation', true, 1),
    item('Snapshot Isolation', true, 1),
    item('Repeatable Read vs Serializable', true, 1),
    item('Write Skew Problem', true, 1),
    item('Replication', true),
    item('Leader-Follower Architecture', true, 1),
    item('Sync vs Async Replication', true, 1),
    item('Replication Lag', true, 1),
    item('Read-After-Write Consistency', true, 1),
    item('Failover Process', true, 1),
    item('Scaling Databases', true),
    item('Vertical Scaling', true, 1),
    item('Horizontal Scaling', true, 1),
    item('Read Replica Limits', true, 1),
    item('Write Bottleneck', true, 1),
    item('Cross-Region Replication Trade-offs', true, 1),
    item('Strong vs Eventual Consistency', true, 1),
    item('Sharding / Partitioning', true, 1),
    item('Range-Based Sharding', true, 2),
    item('Hash-Based Sharding', true, 2),
    item('Directory-Based Sharding', true, 2),
    item('Consistent Hashing', true, 2),
    item('Rebalancing Strategy', true, 2),
    item('Hot Partition Issue', true, 2),
    item('Cross-Shard Joins', true, 2),
    item('Global Secondary Indexes', true, 2),
    item('NoSQL', true),
    item('Key-Value Stores', true, 1),
    item('Document Databases', true, 1),
    item('Column Stores', true, 1),
    item('Graph Databases', true, 1),
    item('When to Prefer Each', true, 1),
    item('Denormalization Trade-offs', true, 1),
    item('Eventual Consistency Behavior', true, 1),
    item('Secondary Index Limitations', true, 1),
    item('Multi-Leader Conflicts', true),
    item('Split Brain', true),
  ]),
  G('Caching', '2️⃣', [
    item('Core Patterns', true),
    item('Cache-Aside', true, 1),
    item('Write-Through', true, 2),
    item('Write-Back', true, 1),
    item('Write-Around', true, 1),
    item('Cache Warming', true, 1),
    item('TTL Strategy Design', true),
    item('Eviction Policies', true),
    item('LRU', true, 1),
    item('LFU', true, 1),
    item('FIFO', true, 1),
    item('Random Eviction', true, 1),
    item('Memory Fragmentation (Internal vs External)', true, 1),
    item('Consistency', false),
    item('Cache Invalidation Strategies', true, 1),
    item('Double Delete Pattern', false, 1),
    item('Stale Data Window', false, 1),
    item('Read-After-Write Inconsistency', false, 1),
    item('Failure Scenarios', false),
    item('Cache Stampede', false, 1),
    item('Thundering Herd', false, 1),
    item('Hot Key Problem', false, 1),
    item('Cache Penetration', false, 1),
    item('Cold Start Problem', false, 1),
    item('Redis Internals', false),
    item('Single-Threaded Event Loop', false, 1),
    item('Why Redis Is Fast', false, 1),
    item('RDB Persistence', false, 1),
    item('AOF Persistence', false, 1),
    item('Replication Model', false, 1),
    item('Sentinel', false, 1),
    item('Cluster Mode', false, 1),
    item('Slot-Based Sharding', false, 1),
  ]),
  G('Async Processing', '3️⃣', [
    item('Messaging Fundamentals', false),
    item('At-Most-Once', false, 1),
    item('At-Least-Once', false, 1),
    item('Exactly-Once (Practical Meaning)', false, 1),
    item('Idempotency', false, 1),
    item('Dead Letter Queue', false, 1),
    item('Retry Strategies', false, 1),
    item('Backpressure Handling', false, 1),
    item('Kafka Internals', false),
    item('Topic Architecture', false, 1),
    item('Partition Strategy', false, 1),
    item('Partition Key Selection', false, 1),
    item('Ordering Guarantees', false, 1),
    item('Offset Management', false, 1),
    item('Consumer Groups', false, 1),
    item('Rebalancing Process', false, 1),
    item('ISR (In-Sync Replicas)', false, 1),
    item('Leader Election', false, 1),
    item('Retention Policies', false, 1),
    item('Log Compaction', false, 1),
    item('Pull Model Rationale', false, 1),
    item('Failure Modes', false),
    item('Producer Retry Duplication', false, 1),
    item('Consumer Crash Mid-Processing', false, 1),
    item('Broker Failure', false, 1),
    item('Network Partition', false, 1),
    item('Data Loss Scenarios', false, 1),
  ]),
  G('Load Balancing & Resiliency', '4️⃣', [
    item('Load Balancers', false),
    item('L4 vs L7', false, 1),
    item('Round Robin', false, 1),
    item('Least Connections', false, 1),
    item('Consistent Hashing', false, 1),
    item('Health Checks', false, 1),
    item('Sticky Sessions', false, 1),
    item('Circuit Breaker', false),
    item('Closed State', false, 1),
    item('Open State', false, 1),
    item('Half-Open State', false, 1),
    item('Fail Fast Principle', false),
    item('Cascading Failure Prevention', false),
    item('Leader Election', false),
    item('Quorum Concept', false),
    item('Raft Basics', false),
    item('Heartbeats', false, 1),
    item('Majority Consensus Logic', false, 1),
  ]),
  G('Estimation Practice', '5️⃣', [
    item('QPS Estimation', false),
    item('Storage Estimation', false),
    item('Bandwidth Estimation', false),
    item('Peak vs Average Traffic', false),
    item('Read/Write Ratio Impact', false),
    item('2-Minute Estimation Drill', false),
  ]),
  G('API Design Principles', '6️⃣', [
    item('When to use (gRPC vs REST)', false),
    item('Protobuf advantages', false),
    item('REST best practices', false),
    item('Stateless', false, 1),
    item('Uniform interface', false, 1),
    item('HATEOAS', false, 1),
    item('GraphQL vs REST', false),
    item('Over-fetching vs under-fetching', false, 1),
    item('Versioning strategies', false),
    item('URL versioning', false, 1),
    item('Header-based versioning', false, 1),
    item('Query parameter versioning', false, 1),
    item('Idempotency', false),
    item('Idempotency-Key header', false, 1),
    item('Pagination', false),
    item('Offset-based pagination', false, 1),
    item('Cursor-based pagination', false, 1),
    item('Sorting & Filtering best practices', false),
    item('Server-side sorting', false, 1),
    item('Multi-field sorting', false, 1),
    item('Filtering with query params', false, 1),
    item('Index optimization', false, 1),
    item('Avoid over-fetching', false, 1),
  ]),
  G('DNS & Traffic Routing', '7️⃣', [
    item('DNS Resolution Flow', false),
    item('Recursive vs Iterative Resolution', false, 1),
    item('Root → TLD → Authoritative flow', false, 1),
    item('Role of DNS Resolver', false, 1),
    item('DNS Caching Layers', false),
    item('Browser Cache', false, 1),
    item('OS Cache', false, 1),
    item('ISP Resolver Cache', false, 1),
    item('TTL impact on freshness', false, 1),
    item('Geo-based Routing', false),
    item('Latency-based routing', false, 1),
    item('Geo DNS vs Anycast', false, 1),
    item('DNS Load Balancing', false),
    item('Round Robin DNS', false, 1),
    item('Health check limitations', false, 1),
    item('Failover challenges', false, 1),
  ]),
  G('CDN', '8️⃣', [
    item('CDN Architecture', false),
    item('Global edge network', false, 1),
    item('Cache hierarchy', false, 1),
    item('Edge vs Origin', false),
    item('Cache hit vs miss flow', false, 1),
    item('Origin shielding', false, 1),
    item('Push vs Pull CDN', false),
    item('Preload vs On-demand caching', false, 1),
    item('Cache Strategies', false),
    item('Static vs Dynamic content caching', false, 1),
    item('TTL tuning', false, 1),
    item('Cache invalidation', false, 1),
    item('Performance Optimization', false),
    item('Latency reduction', false, 1),
    item('Bandwidth savings', false, 1),
  ]),
  G('Proxies', '9️⃣', [
    item('Forward Proxy', false),
    item('Client-side proxying', false, 1),
    item('Use cases (privacy, filtering)', false, 1),
    item('Reverse Proxy', false),
    item('Server-side proxying', false, 1),
    item('Load distribution', false, 1),
    item('Proxy vs Load Balancer', false),
    item('L7 overlap', false, 1),
    item('Routing vs distribution', false, 1),
    item('VPN vs Proxy', false),
    item('Encryption differences', false, 1),
    item('Network-level vs app-level', false, 1),
  ]),
  G('Core Distributed System Characteristics', '🔟', [
    item('Scalability', false),
    item('Horizontal scaling patterns', false, 1),
    item('Auto-scaling triggers', false, 1),
    item('Availability', false),
    item('SLA / SLO basics', false, 1),
    item('Downtime impact', false, 1),
    item('Latency vs Throughput', false),
    item('Tail latency (P99)', false, 1),
    item('Tradeoffs', false, 1),
    item('Concurrency & Coordination', false),
    item('Locks vs lock-free systems', false, 1),
    item('Distributed coordination basics', false, 1),
    item('Observability', false),
    item('Metrics (CPU, memory, QPS)', false, 1),
    item('Logging', false, 1),
    item('Tracing', false, 1),
    item('Resilience & Error Handling', false),
    item('Retry storms', false, 1),
    item('Backoff strategies', false, 1),
    item('Fault Tolerance', false),
    item('Redundancy strategies', false, 1),
    item('Failover mechanisms', false, 1),
  ]),
  G('Network Essentials', '1️⃣1️⃣', [
    item('HTTP vs HTTPS', false),
    item('TLS handshake basics', false, 1),
    item('Certificate validation', false, 1),
    item('Encryption overhead vs security benefits', false, 1),
    item('TCP vs UDP', false),
    item('Connection-oriented vs connectionless', false, 1),
    item('Reliability (retransmission, ordering)', false, 1),
    item('Use cases (APIs vs streaming/gaming)', false, 1),
    item('HTTP Versions', false),
    item('HTTP/1.1: Head-of-line blocking', false, 1),
    item('HTTP/1.1: Keep-alive connections', false, 1),
    item('HTTP/2: Multiplexing', false, 1),
    item('HTTP/2: Header compression (HPACK)', false, 1),
    item('HTTP/3: QUIC over UDP', false, 1),
    item('HTTP/3: Reduced latency (0-RTT)', false, 1),
    item('URL vs URI vs URN', false),
    item('URI as identifier', false, 1),
    item('URL as locator', false, 1),
    item('URN as name-based identifier', false, 1),
  ]),
  G('Data Integrity & System Signals', '1️⃣5️⃣', [
    item('Checksum', false),
    item('Data integrity verification', false, 1),
    item('Corruption detection', false, 1),
    item('Heartbeat Mechanism', false),
    item('Node liveness detection', false, 1),
    item('Failure detection timing', false, 1),
    item('Leader–Follower Pattern', false),
    item('Write leader', false, 1),
    item('Read replicas', false, 1),
    item('Failover switching', false, 1),
    item('Quorum Concept', false),
    item('Read quorum (R)', false, 1),
    item('Write quorum (W)', false, 1),
    item('R + W > N rule', false, 1),
  ]),
  G('Security', '1️⃣6️⃣', [
    item('Authentication', false),
    item('Session-based auth', false, 1),
    item('Token-based auth', false, 1),
    item('Authorization', false),
    item('RBAC', false, 1),
    item('ABAC', false, 1),
    item('OAuth vs JWT', false),
    item('Token flow', false, 1),
    item('Stateless authentication', false, 1),
    item('Encryption', false),
    item('At rest', false, 1),
    item('In transit (TLS)', false, 1),
    item('DDoS Protection', false),
    item('Rate limiting', false, 1),
    item('Traffic filtering', false, 1),
    item('CDN protection', false, 1),
  ]),
  G('Distributed File Systems', '1️⃣7️⃣', [
    item('DFS Architecture', false),
    item('Master node', false, 1),
    item('Worker nodes', false, 1),
    item('Storage Model', false),
    item('Block-based storage', false, 1),
    item('File chunking', false, 1),
    item('Replication', false),
    item('Multi-node redundancy', false, 1),
    item('Data consistency', false, 1),
    item('Fault Handling', false),
    item('Node failure recovery', false, 1),
    item('Re-replication mechanisms', false, 1),
  ]),
  G('Bloom Filters', '1️⃣8️⃣', [
    item('Core Concept', false),
    item('Probabilistic membership check', false, 1),
    item('Internal Working', false),
    item('Hash functions', false, 1),
    item('Bit array mapping', false, 1),
    item('Tradeoffs', false),
    item('False positives', false, 1),
    item('No false negatives', false, 1),
    item('Use Cases', false),
    item('Cache filtering', false, 1),
    item('Database query optimization', false, 1),
  ]),
  G('Real-Time Communication', '1️⃣9️⃣', [
    item('Long Polling', false),
    item('Client waits for response', false, 1),
    item('WebSockets', false),
    item('Full-duplex communication', false, 1),
    item('Server-Sent Events (SSE)', false),
    item('One-way streaming', false, 1),
    item('Tradeoffs', false),
    item('Scalability vs latency', false, 1),
  ]),
  G('System Design Tradeoffs', '2️⃣0️⃣', [
    item('CAP Theorem', false),
    item('Consistency vs Availability', false, 1),
    item('Partition tolerance', false, 1),
    item('PACELC Theorem', false),
    item('Latency vs Consistency tradeoff', false, 1),
    item('Real-world Tradeoffs', false),
    item('Strong vs Eventual consistency', false, 1),
    item('Cost vs performance', false, 1),
    item('Simplicity vs scalability', false, 1),
  ]),
];

export default groups;
